name: Go Unit Tests

on:
  push:
    branches:
      - master

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.6'

      - name: Build
        run: go build -o build/ -v ./...

      - name: Run
        run: ./build/pentest_tools &

      - name: Test
        run: go test -v ./tests
